#!/usr/bin/env bash
# Installs and configures UFW to block incoming traffic except ports 22, 443, and 80

sudo apt-get update -y
sudo apt-get install -y ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
echo "y" | sudo ufw enable
