#!/usr/bin/env bash
# Script that audits subdomains using dig and awk

domain="$1"
subdomain="$2"

lookup_subdomain() {
    local sub="$1"
    # Query DNS using dig and use awk to extract record type and IP
    dig "${sub}.${domain}" A +noall +answer | awk -v sub="$sub" '
    $4 == "A" {
        print "The subdomain " sub " is a A record and points to " $5
    }'
}

if [ -n "$subdomain" ]; then
    lookup_subdomain "$subdomain"
else
    for sub in www lb-01 web-01 web-02; do
        lookup_subdomain "$sub"
    done
fi
