#!/usr/bin/env bash
# Installs and configures HAProxy on lb-01

sudo apt-get update -y
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

if ! grep -q "frontend http_front" /etc/haproxy/haproxy.cfg; then
cat << 'HAPROXY_CONF' | sudo tee -a /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 3.95.178.242:80 check
    server web-02 44.204.175.102:80 check
HAPROXY_CONF
fi

sudo service haproxy restart
